### ISSUE TITLE
Cannot use this in Svelte with Type: Module when running in development mode

### ISSUE THREAD

**Issue by NathanNobert** [beyonk-group/gdpr-cookie-consent-banner#47]
I receive an error when trying to use this in a project when running locally using Svelte. The error is:
```
 The requested module '/node_modules/.vite/deps/@beyonk_gdpr-cookie-consent-banner.js?v=6c7b1300' does not provide an export named 'default'
```

I believe this is due to my Svelte project using Modules and typescript, as in my package.json file I have:
```
"type": "module"
```

I do not receive this error when building and deploying to production however.

**Comment by 0gust1** [comment]
Try adding
```js
  optimizeDeps: {
    exclude: ['@beyonk/gdpr-cookie-consent-banner']
  }
```
in your `vite.config.js` or `vite.config.ts` file

**Comment by 0gust1** [comment]
Small note for Sveltekit users:  
the vite trick above seems not necessary anymore with the ^10.0.0 version of this package!
