### ISSUE TITLE
update to ^10.0.0 in Sveltekit project: minor TS error

### ISSUE THREAD

**Issue by 0gust1** [beyonk-group/gdpr-cookie-consent-banner#48]
Just updated the component in our Sveltekit-based project:
- now it works without this vite trick: https://github.com/beyonk-adventures/gdpr-cookie-consent-banner/issues/47#issuecomment-1495172142 (**thanks and congrats!**)
- Our project is in Typescript and I noticed this small error:
<img width="636" alt="Capture d’écran 2023-05-02 à 18 08 14" src="https://user-images.githubusercontent.com/578154/235722857-06765681-822f-4628-8287-de51fafb7cf8.png">

**Comment by antony** [comment]
Yeah I'm no TS expert unfortunately. If somebody knows how to fix this they probably should!
