### ISSUE TITLE
Suggestion: Disable tabbing behind the cookie banner

### ISSUE THREAD

**Issue by enisbudancamanak** [beyonk-group/gdpr-cookie-consent-banner#54]
Its possible to tab behind the cookie banner, is there a way to disable it?

**Comment by antony** [comment]
Essentially to make the cookie banner a modal? I'm not sure that's desirable. I suppose it could be an option.

**Comment by antony** [comment]
Closing this as I don't think it's the done thing to enforce acceptance of the cookie banner.
